@startuml

abstract class UI {

}

class Bilet{
    cel 
    termin
    cena 
    klasa 
    miejsce_w_pociagu
    czas_sprzedarzy
}

class Paragon{
    'bilet zamieniono na asocjację z klasą Bilet
    cena
    VAT
}

class Kasjer{
    ID 
    imie
    nazwisko
}

class Kasa{
    stan
    stan_platnosci_bezgotowkowych
    wplata()
}

class Biletomat{
    kupno()
}

class Drukarka{
    wydruk()
}

class Dostep_do_Danych{
wyszukaj_polaczenie()
zapisz_transakcje()
}

interface Baza_Danych{
}

interface Bank{
    autoryzacja()
}


Kasjer -- Kasa
Bilet -- "bilet" Paragon
Biletomat "kasa" -- Kasa
Biletomat .. Bilet : <<create>>
Biletomat .. Paragon : <<create>>
UI -- Biletomat
Biletomat o- Drukarka
Biletomat -- Dostep_do_Danych
Dostep_do_Danych -- Baza_Danych
Kasa -- Bank

ConsoleUI --|>UI
GUI --|> UI
DukarkaParagonow --|> Drukarka
DrukarkaBiletow --|> Drukarka
@enduml