@startuml

class Bilet{
    miejsce_docelowe
    siedzenie
    termin_podrozy
    cena 
    czas_zakupu
    'paragon opisane przez asocjację
}

class Paragon{
    'bilet opisane przez asocjację
    cena
    vat
}


class Kasjer{

}

class Biletomat{
    zakup(cel_podrozy)
    wplata(bilet, kwota)
}

class Kasa{
    stan
    stan_bezgotowkowy
    wplata()
}

interface Bank{
    autoryzacja()
}

abstract class UI{}

class Drukarka{}

class Operacje_na_danych{
    wyszukaj_polaczenia()
}

interface Baza_Danych{
    informacje_o_polaczeniach
    informacja_o_transakcjach
}

Paragon "bilet" -- "paragon" Bilet
Biletomat -- Kasa
Kasjer -- Kasa 
DrukarkaParagonow --|> Drukarka
DrukarkaBiletow --|> Drukarka
Biletomat -- Drukarka
UI -- Biletomat
ConsoleUI --|> UI
GUI --|> UI
WebUI --|> UI
Operacje_na_danych -- Baza_Danych
Biletomat -- Operacje_na_danych
Kasa -- Bank

Biletomat .. Bilet : <<create>>
Biletomat .. Paragon : <<create>>
@enduml