@startuml

class Bilet{
    miejsce_docelowe
    siedzenie
    termin_podrozy
    cena 
    czas_zakupu
    'paragon opisane przez asocjację
}

class Paragon{
    'bilet opisane przez asocjację
    cena
    vat
}


class Kasjer{

}

class Biletomat{
    zakup(cel_podrozy)
    wplata(bilet, kwota)
}

class Kasa{
    stan
    wplata()
}

class UI{}

class Drukarka{}



Paragon "bilet" -- "paragon" Bilet
Biletomat -- Kasa
Kasjer -- Kasa 
DrukarkaParagonow --|> Drukarka
DrukarkaBiletow --|> Drukarka
Biletomat -- Drukarka
UI -- Biletomat
ConsoleUI --|> UI
GUI --|> UI
WebUI --|> UI
@enduml